apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  RATESHOP_FRONTEND_URL: "http://a4996b22c82a443e7a68a26940e7f1f4-310303567.us-east-2.elb.amazonaws.com" #LoadBalancer externalIP
  REACT_APP_RATESHOP_BACKEND_URL: "http://a1ed7597d170a46aeaf2a940caf05159-690899401.us-east-2.elb.amazonaws.com:8080/fleet" #LoadBalancer externalIP
  RENT_PREDICTOR_URL: "http://rent-predictor-service:8000" # URL for the rent predictor service
