apiVersion: apps/v1
kind: Deployment
metadata:
  name: rateshop-frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rateshop-frontend
  template:
    metadata:
      labels:
        app: rateshop-frontend
    spec:
      containers:
        - name: rateshop-frontend
          image: 522814708632.dkr.ecr.us-east-2.amazonaws.com/rateshop-frontend:latest
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_RATESHOP_BACKEND_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: REACT_APP_RATESHOP_BACKEND_URL
---
apiVersion: v1
kind: Service
metadata:
  name: rateshop-frontend-service
spec:
  selector:
    app: rateshop-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
